services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
      - "${RABBIT_GUI_PORT}:${RABBIT_GUI_PORT}"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    volumes:
      - rmq_data:/var/lib/rabbitmq
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis

volumes:
  rmq_data:
