services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    volumes:
      - rmq_data:/var/lib/rabbitmq
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  rmq_data:
