services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
      - "${RABBIT_GUI_PORT}:${RABBIT_GUI_PORT}"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    volumes:
      - rmq_data:/var/lib/rabbitmq
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    command: >
      sh -c "uvicorn main:app --reload --host ${APP_HOST} --port ${APP_PORT}"
    depends_on:
      - rabbitmq
      - redis
  celery_worker:
    build: .
    env_file:
      - .env
    command: celery --app=celery_base.celery_app:celery_app worker --pool=solo
    depends_on:
      - app
  celery_flower:
    build: .
    env_file:
      - .env
    ports:
      - "${FLOWER_HOST_PORT}:${FLOWER_CONTAINER_PORT}"
    command: celery --app=celery_base.celery_app:celery_app flower --port=${FLOWER_CONTAINER_PORT}
    depends_on:
      - celery_worker

volumes:
  rmq_data:
